Repository codesquad-members-2023/issue-tracker, pull requests merged in 2023-05, with the labels that each got.

#15 [TEAM-05][BE : NINO,고뭉남] Issue-Tracker 1주차 PR
  .github/ISSUE_TEMPLATE/be-issue-template.md
  .github/ISSUE_TEMPLATE/fe-issue-template.md
  .github/ISSUE_TEMPLATE/ios-issue-template.md
  BE/README.md
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/issuetracker/IssueTrackerApplication.java
  BE/src/main/resources/application.properties
  BE/src/test/java/issuetracker/IssueTrackerApplicationTests.java
  FE/README.md
  README.md
  iOS/README.md
Labels: review-be

#20 [team-04] iOS 프로젝트를 생성하였습니다
  .github/.gitmessage.txt
  .github/ISSUE_TEMPLATE/teamp04-issue-template.md
  README.md
  iOS/.gitignore
  iOS/IssueTracker/.swiftlint.yml
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/IssueTracker/IssueTracker.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/IssueTracker/IssueTracker/Application/AppDelegate.swift
  iOS/IssueTracker/IssueTracker/Application/SceneDelegate.swift
  iOS/IssueTracker/IssueTracker/Global/Literal/ColorStyle.swift
  iOS/IssueTracker/IssueTracker/Global/Literal/ComponentStyle.swift
  iOS/IssueTracker/IssueTracker/Global/Literal/FontStyle.swift
  iOS/IssueTracker/IssueTracker/Global/Literal/ImageMapper.swift
  iOS/IssueTracker/IssueTracker/Presentation/Common/View/Base.lproj/IssueTrackerTabBar.storyboard
  iOS/IssueTracker/IssueTracker/Presentation/Common/ViewController/IssueTrackerTabBarController.swift
  iOS/IssueTracker/IssueTracker/Presentation/Launch/View/Base.lproj/LaunchScreen.storyboard
  iOS/IssueTracker/IssueTracker/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  iOS/IssueTracker/IssueTracker/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/IssueTracker/IssueTracker/Resource/Assets.xcassets/Color/Contents.json
  iOS/IssueTracker/IssueTracker/Resource/Assets.xcassets/Color/gray100.colorset/Contents.json
  iOS/IssueTracker/IssueTracker/Resource/Assets.xcassets/Color/gray200.colorset/Contents.json
  iOS/IssueTracker/IssueTracker/Resource/Assets.xcassets/Color/gray300.colorset/Contents.json
  iOS/IssueTracker/IssueTracker/Resource/Assets.xcassets/Color/gray400.colorset/Contents.json
  iOS/IssueTracker/IssueTracker/Resource/Assets.xcassets/Color/gray50.colorset/Contents.json
  iOS/IssueTracker/IssueTracker/Resource/Assets.xcassets/Color/gray500.colorset/Contents.json
  iOS/IssueTracker/IssueTracker/Resource/Assets.xcassets/Color/gray600.colorset/Contents.json
  iOS/IssueTracker/IssueTracker/Resource/Assets.xcassets/Color/gray700.colorset/Contents.json
  iOS/IssueTracker/IssueTracker/Resource/Assets.xcassets/Color/gray800.colorset/Contents.json
  iOS/IssueTracker/IssueTracker/Resource/Assets.xcassets/Color/gray900.colorset/Contents.json
  iOS/IssueTracker/IssueTracker/Resource/Assets.xcassets/Color/issueTrackerBlue.colorset/Contents.json
  iOS/IssueTracker/IssueTracker/Resource/Assets.xcassets/Color/issueTrackerPurple.colorset/Contents.json
  iOS/IssueTracker/IssueTracker/Resource/Assets.xcassets/Color/issueTrackerRed.colorset/Contents.json
  iOS/IssueTracker/IssueTracker/Resource/Assets.xcassets/Contents.json
  iOS/IssueTracker/IssueTracker/Resource/Assets.xcassets/Image/Contents.json
  iOS/IssueTracker/IssueTracker/Resource/Assets.xcassets/Image/Exclamation.imageset/Contents.json
  iOS/IssueTracker/IssueTracker/Resource/Assets.xcassets/Image/Exclamation.imageset/exclamation.svg
  iOS/IssueTracker/IssueTracker/Resource/Assets.xcassets/Image/LogotypeMedium.imageset/Contents.json
  iOS/IssueTracker/IssueTracker/Resource/Assets.xcassets/Image/LogotypeMedium.imageset/LogotypeMedium.svg
  iOS/IssueTracker/IssueTracker/Resource/Assets.xcassets/Image/Milestone.imageset/Contents.json
  iOS/IssueTracker/IssueTracker/Resource/Assets.xcassets/Image/Milestone.imageset/milestone.svg
  iOS/IssueTracker/IssueTracker/Resource/Assets.xcassets/Image/ProfileL.imageset/Contents.json
  iOS/IssueTracker/IssueTracker/Resource/Assets.xcassets/Image/ProfileL.imageset/profileL.svg
  iOS/IssueTracker/IssueTracker/Resource/Assets.xcassets/Image/ProfileS.imageset/Contents.json
  iOS/IssueTracker/IssueTracker/Resource/Assets.xcassets/Image/ProfileS.imageset/profileS.svg
  iOS/IssueTracker/IssueTracker/Resource/Assets.xcassets/Image/Smile.imageset/Contents.json
  iOS/IssueTracker/IssueTracker/Resource/Assets.xcassets/Image/Smile.imageset/smile.svg
  iOS/IssueTracker/IssueTracker/Resource/Assets.xcassets/Image/Tag.imageset/Contents.json
  iOS/IssueTracker/IssueTracker/Resource/Assets.xcassets/Image/Tag.imageset/tag.svg
  iOS/IssueTracker/IssueTracker/Resource/Info.plist
Labels: review-ios

#25 [team-01] BE 1주차 리뷰 PR
  .github/.gitmessage.txt
  .github/ISSUE_TEMPLATE/feature.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .idea/.gitignore
  BE/README.md
  BE/요구사항분석.md
  README.md
Labels: review-be

#14 [team-06] 프론트엔드 리뷰 1주차 PR
  .gitignore
  README.md
  frontend/.eslintignore
  frontend/.eslintrc.json
  frontend/.gitignore
  frontend/.prettierignore
  frontend/.prettierrc.json
  frontend/README.md
  frontend/config-overrides.js
  frontend/jsconfig.json
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/public/mockServiceWorker.js
  frontend/public/robots.txt
  frontend/src/App.js
  frontend/src/assets/icons/alertCircle.svg
  frontend/src/assets/icons/archive.svg
  frontend/src/assets/icons/calendar.svg
  frontend/src/assets/icons/checkBoxActive.svg
  frontend/src/assets/icons/checkBoxDisable.svg
  frontend/src/assets/icons/checkBoxInitial.svg
  frontend/src/assets/icons/checkOffCircle.svg
  frontend/src/assets/icons/checkOnCircle.svg
  frontend/src/assets/icons/chevronDown.svg
  frontend/src/assets/icons/edit.svg
  frontend/src/assets/icons/index.jsx
  frontend/src/assets/icons/label.svg
  frontend/src/assets/icons/milestone.svg
  frontend/src/assets/icons/paperclip.svg
  frontend/src/assets/icons/plus.svg
  frontend/src/assets/icons/refreshCcw.svg
  frontend/src/assets/icons/search.svg
  frontend/src/assets/icons/smile.svg
  frontend/src/assets/icons/trash.svg
  frontend/src/assets/icons/userImageLarge.svg
  frontend/src/assets/icons/userImageSmall.svg
  frontend/src/assets/icons/xSquare.svg
  frontend/src/components/Button/Button.jsx
  frontend/src/components/Button/Button.module.css
  frontend/src/components/Dropdown/Dropdown.jsx
  frontend/src/components/Dropdown/Dropdown.module.css
  frontend/src/components/Dropdown/DropdownElement/DropdownElement.jsx
  frontend/src/components/Icon/Icon.jsx
  frontend/src/components/InformationTag/InformationTag.jsx
  frontend/src/components/InformationTag/InformationTag.module.css
  frontend/src/components/index.jsx
  frontend/src/containers/IssuePage/IssuePage.jsx
  frontend/src/index.js
  frontend/src/logo.svg
  frontend/src/mocks/browser.js
  frontend/src/mocks/handler.js
  frontend/src/reportWebVitals.js
  frontend/src/setupTests.js
  frontend/src/styles/global.module.css
  frontend/src/styles/reset.css
Labels: review-fe

#22 [team-04] FE 1주차 설계 및 초기 환경 설정
  FE/ .eslintignore
  FE/ .prettierrc.json
  FE/.eslintrc.json
  FE/.gitignore
  FE/README.md
  FE/package-lock.json
  FE/package.json
  FE/public/favicon.ico
  FE/public/index.html
  FE/public/logo192.png
  FE/public/logo512.png
  FE/public/manifest.json
  FE/public/mockServiceWorker.js
  FE/public/robots.txt
  FE/src/App.css
  FE/src/App.jsx
  FE/src/index.jsx
  FE/src/mocks/browser.js
  FE/src/mocks/handler.js
  FE/src/pages/IssueList.jsx
  FE/src/styles/GlobalStyle.js
  FE/src/styles/color.js
  FE/src/styles/font.js
  README.md
Labels: review-fe

#17 [BE 03] DB 모델링 및 DB 테이블 생성 / DTO 설계 / 인프라 구축 / API 명세서 작성
  .github/ISSUE_TEMPLATE/feature_request.md
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/com/example/BE/BeApplication.java
  BE/src/main/java/com/example/BE/dto/show/issue/FeIssueResponse.java
  BE/src/main/java/com/example/BE/dto/show/issue/detailed/CountForShow.java
  BE/src/main/java/com/example/BE/dto/show/issue/detailed/FeSimpleIssue.java
  BE/src/main/java/com/example/BE/dto/show/issue/detailed/SimpleAuthor.java
  BE/src/main/java/com/example/BE/dto/show/issue/detailed/SimpleLabel.java
  BE/src/main/java/com/example/BE/dto/show/issue/detailed/SimpleMilestone.java
  BE/src/main/java/com/example/BE/test/TestController.java
  BE/src/main/java/com/example/BE/test/TestDTO.java
  BE/src/main/resources/create_table.sql
  BE/src/main/resources/dummy_data.sql
  BE/src/test/java/com/example/BE/BeApplicationTests.java
  README.md
Labels: review-be

#21 [team-05 - iOS] Issue-Tracker 1주차 PR
  iOS/.gitignore
  iOS/issue-tracker/.swiftlint.yml
  iOS/issue-tracker/Podfile
  iOS/issue-tracker/issue-tracker.xcodeproj/project.pbxproj
  iOS/issue-tracker/issue-tracker.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/issue-tracker/issue-tracker.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/issue-tracker/issue-tracker.xcodeproj/project.xcworkspace/xcuserdata/pjb.xcuserdatad/UserInterfaceState.xcuserstate
  iOS/issue-tracker/issue-tracker.xcodeproj/xcuserdata/pjb.xcuserdatad/xcschemes/xcschememanagement.plist
  iOS/issue-tracker/issue-tracker/AppDelegate.swift
  iOS/issue-tracker/issue-tracker/Assets.xcassets/AccentColor.colorset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/Issue_Symbol.imageset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/Issue_Symbol.imageset/Issue_Symbol.svg
  iOS/issue-tracker/issue-tracker/Assets.xcassets/Label_Symbol.imageset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/Label_Symbol.imageset/Label_Symbol.svg
  iOS/issue-tracker/issue-tracker/Assets.xcassets/Milestone_Symbol.imageset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/Milestone_Symbol.imageset/Milestone_Symbol.svg
  iOS/issue-tracker/issue-tracker/Base.lproj/LaunchScreen.storyboard
  iOS/issue-tracker/issue-tracker/Info.plist
  iOS/issue-tracker/issue-tracker/IssueViewController.swift
  iOS/issue-tracker/issue-tracker/LabelViewController.swift
  iOS/issue-tracker/issue-tracker/MileStoneViewController.swift
  iOS/issue-tracker/issue-tracker/SceneDelegate.swift
  iOS/issue-tracker/issue-tracker/SymbolImage.swift
  iOS/issue-tracker/issue-tracker/TabBarViewController.swift
Labels: review-ios

#36 [team-01] FE 2주차 리뷰 PR
  fe/.eslintrc.json
  fe/package-lock.json
  fe/package.json
  fe/public/index.html
  fe/public/logo192.png
  fe/public/logo512.png
  fe/public/manifest.json
  fe/public/robots.txt
  fe/src/App.css
  fe/src/App.js
  fe/src/App.test.js
  fe/src/assets/icons/CloseIssueStatusIcon.svg
  fe/src/assets/icons/DropdownIcon.svg
  fe/src/assets/icons/MilestoneIcon.svg
  fe/src/assets/icons/OpenIssueStatusIcon.svg
  fe/src/assets/icons/PlusIcon.svg
  fe/src/assets/images/logo.svg
  fe/src/assets/images/userImageLarge.svg
  fe/src/assets/userImage/UserImage.svg
  fe/src/common/Checkbox.jsx
  fe/src/common/button/Button.jsx
  fe/src/common/header/Header.jsx
  fe/src/common/tabs/Tabs.jsx
  fe/src/components/mainPage/issueTable/IssueTable.jsx
  fe/src/components/mainPage/issueTable/header/IssueTableHeader.jsx
  fe/src/components/mainPage/issueTable/header/headerLeft/IssueStatusButton.jsx
  fe/src/components/mainPage/issueTable/header/headerLeft/IssueTableHeaderLeft.jsx
  fe/src/components/mainPage/issueTable/header/headerRight/IssueFilterButton.jsx
  fe/src/components/mainPage/issueTable/header/headerRight/IssueTableHeaderRight.jsx
  fe/src/components/mainPage/issueTable/list/IssueTableList.jsx
  fe/src/components/mainPage/issueTable/list/listItems/IssueTableListItem.jsx
  fe/src/components/mainPage/issueTable/list/listItems/Label.jsx
  fe/src/components/mainPage/nav/Nav.jsx
  fe/src/components/mainPage/nav/filterBar/FilterBar.jsx
  fe/src/index.css
  fe/src/index.js
  fe/src/logo.svg
  fe/src/mocks/handler.js
  fe/src/mocks/worker.js
  fe/src/pages/MainPage.jsx
  fe/src/reportWebVitals.js
  fe/src/setupTests.js
  fe/src/styles/GlobalStyle.jsx
  fe/src/styles/theme.js
Labels: review-fe

#39 [Team-04] 2주차 스프린트 작업 내용입니다
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Global/Literal/ComponentStyle.swift
  iOS/IssueTracker/IssueTracker/Global/Literal/FontStyle.swift
  iOS/IssueTracker/IssueTracker/Presentation/Issue/View/IssueCommentCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/Presentation/Issue/View/IssueCommentCollectionViewCell.xib
  iOS/IssueTracker/IssueTracker/Presentation/Issue/View/IssueHeaderCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/Presentation/Issue/View/IssueHeaderCollectionViewCell.xib
  iOS/IssueTracker/IssueTracker/Presentation/Issue/View/IssueListCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/Presentation/Issue/View/IssueListCollectionViewCell.xib
  iOS/IssueTracker/IssueTracker/Presentation/Label/View/LabelCollectionViewCell.xib
  iOS/IssueTracker/IssueTracker/Presentation/Label/ViewController/LabelCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/Presentation/Milestone/View/MilestoneCollectionViewCell.xib
  iOS/IssueTracker/IssueTracker/Presentation/Milestone/ViewController/MilestoneCollectionViewCell.swift
Labels: review-ios

#43 [team-03 : iOS] 2주차 이슈목록 UI 추가 구현 및 model 설계
  README.md
  iOS/issue-tracker/Podfile
  iOS/issue-tracker/Podfile.lock
  iOS/issue-tracker/issue-tracker.xcodeproj/project.pbxproj
  iOS/issue-tracker/issue-tracker/Assets.xcassets/property=exclamation.imageset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/property=exclamation.imageset/property=exclamation.svg
  iOS/issue-tracker/issue-tracker/Assets.xcassets/property=milestone.imageset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/property=milestone.imageset/property=milestone.svg
  iOS/issue-tracker/issue-tracker/Assets.xcassets/property=smile.imageset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/property=smile.imageset/property=smile.png
  iOS/issue-tracker/issue-tracker/Assets.xcassets/property=tag.imageset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/property=tag.imageset/property=tag.svg
  iOS/issue-tracker/issue-tracker/Home/HomeStoryboard.storyboard
  iOS/issue-tracker/issue-tracker/Home/HomeViewController.swift
  iOS/issue-tracker/issue-tracker/Home/Issue/CollectionView.xib
  iOS/issue-tracker/issue-tracker/Home/Issue/CollectionViewController.swift
  iOS/issue-tracker/issue-tracker/Home/Issue/Controllers/IssueFilterTableViewController.swift
  iOS/issue-tracker/issue-tracker/Home/Issue/Controllers/IssueTabViewController.swift
  iOS/issue-tracker/issue-tracker/Home/Issue/IssueCollectionViewCell.swift
  iOS/issue-tracker/issue-tracker/Home/Issue/IssueFilterTableViewCell.swift
  iOS/issue-tracker/issue-tracker/Home/Issue/Models/Author.swift
  iOS/issue-tracker/issue-tracker/Home/Issue/Models/Contents.swift
  iOS/issue-tracker/issue-tracker/Home/Issue/Models/Issue.swift
  iOS/issue-tracker/issue-tracker/Home/Issue/Models/IssueFrame.swift
  iOS/issue-tracker/issue-tracker/Home/Issue/Models/Label.swift
  iOS/issue-tracker/issue-tracker/Home/Issue/Models/Milestone.swift
  iOS/issue-tracker/issue-tracker/Home/Issue/Models/State.swift
  iOS/issue-tracker/issue-tracker/Home/Issue/Models/Title.swift
  iOS/issue-tracker/issue-tracker/Home/Issue/Views/BadgeLabel.swift
  iOS/issue-tracker/issue-tracker/Home/Issue/Views/IssueCollectionView.swift
  iOS/issue-tracker/issue-tracker/Home/Issue/Views/IssueCollectionViewCell.swift
  iOS/issue-tracker/issue-tracker/Home/Issue/Views/IssueCollectionViewCell.xib
  iOS/issue-tracker/issue-tracker/Home/Issue/Views/IssueCollectionViewHeaderCell.swift
  iOS/issue-tracker/issue-tracker/Home/Issue/Views/IssueCollectionViewHeaderCell.xib
  iOS/issue-tracker/issue-tracker/Home/Issue/Views/IssueFilterTableViewCell.swift
  iOS/issue-tracker/issue-tracker/Home/Issue/Views/IssueFilterTableViewCell.xib
  iOS/issue-tracker/issue-tracker/Home/Issue/Views/SubIconView.swift
  iOS/issue-tracker/issue-tracker/Login/Base.lproj/Main.storyboard
  iOS/issue-tracker/issue-tracker/Login/LoginViewController.swift
  iOS/issue-tracker/issue-tracker/Networking/HTTPDataFetcher.swift
Labels: review-ios

#31 [team-06] 인프라 설계 수정 / 연관관계 없는 Entity CRUD 테스트
  .github/workflows/deploy.yml
  .gitignore
  README.md
  appspec.yml
  backend/build.gradle
  backend/src/main/java/com/team6/issue_tracker/adapter/configuration/AwsConfig.java
  backend/src/main/java/com/team6/issue_tracker/adapter/configuration/SwaggerConfig.java
  backend/src/main/java/com/team6/issue_tracker/adapter/configuration/WebConfig.java
  backend/src/main/java/com/team6/issue_tracker/cloud/ImageHostContorller.java
  backend/src/main/java/com/team6/issue_tracker/comment/CommentRepository.java
  backend/src/main/java/com/team6/issue_tracker/comment/domain/Comment.java
  backend/src/main/java/com/team6/issue_tracker/comment/domain/CommentContents.java
  backend/src/main/java/com/team6/issue_tracker/member/FooController.java
  backend/src/main/java/com/team6/issue_tracker/member/MemberRepository.java
  backend/src/main/java/com/team6/issue_tracker/member/domain/GithubState.java
  backend/src/main/java/com/team6/issue_tracker/member/domain/Member.java
  backend/src/main/java/com/team6/issue_tracker/member/dto/MemberTestResponse.java
  backend/src/test/java/com/team6/issue_tracker/comment/CommentRepositoryTest.java
  backend/src/test/java/com/team6/issue_tracker/member/MemberRepositoryTest.java
  deploy.sh
Labels: review-be

#37 [TEAM-05][BE : NINO,고뭉남] Issue-Tracker 2주차 PR
  BE/README.md
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradlew.bat
  BE/src/main/java/team05/codesquad/issuetracker/IssueTrackerApplication.java
  BE/src/main/java/team05/codesquad/issuetracker/auth/AWSCredentialsProperties.java
  BE/src/main/java/team05/codesquad/issuetracker/auth/S3Properties.java
  BE/src/main/java/team05/codesquad/issuetracker/config/AmazonS3Config.java
  BE/src/main/java/team05/codesquad/issuetracker/config/S3Uploader.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/IssueController.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/S3TestController.java
  BE/src/main/java/team05/codesquad/issuetracker/domain/comment/Comment.java
  BE/src/main/java/team05/codesquad/issuetracker/domain/issue/Issue.java
  BE/src/main/java/team05/codesquad/issuetracker/domain/label/Label.java
  BE/src/main/java/team05/codesquad/issuetracker/domain/member/Member.java
  BE/src/main/java/team05/codesquad/issuetracker/domain/milestone/Milestone.java
  BE/src/main/java/team05/codesquad/issuetracker/repository/CommentRepository.java
  BE/src/main/java/team05/codesquad/issuetracker/repository/IssueRepository.java
  BE/src/main/java/team05/codesquad/issuetracker/repository/LabelRepository.java
  BE/src/main/java/team05/codesquad/issuetracker/repository/MemberRepository.java
  BE/src/main/java/team05/codesquad/issuetracker/repository/MilestoneRepository.java
  BE/src/main/java/team05/codesquad/issuetracker/service/IssueService.java
  BE/src/main/java/team05/codesquad/issuetracker/service/MemberService.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/schema.sql
  BE/src/test/java/team05/codesquad/issuetracker/IssueTrackerApplicationTests.java
  BE/src/test/java/team05/codesquad/issuetracker/controller/IssueControllerTest.java
  BE/src/test/java/team05/codesquad/issuetracker/repository/IssueRepositoryTest.java
Labels: review-be

#38 [team-05] iOS IssueListView와 IssueFilterView 구현
  iOS/issue-tracker/.swiftlint.yml
  iOS/issue-tracker/issue-tracker.xcodeproj/project.pbxproj
  iOS/issue-tracker/issue-tracker/Assets.xcassets/Color/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/Color/blue.colorset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/Color/gray100.colorset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/Color/gray200.colorset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/Color/gray300.colorset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/Color/gray400.colorset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/Color/gray50.colorset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/Color/gray500.colorset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/Color/gray600.colorset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/Color/gray700.colorset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/Color/gray800.colorset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/Color/gray900.colorset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/Color/purple.colorset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/Color/red.colorset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/TabBar_Symbol/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/TabBar_Symbol/Issue_Symbol.imageset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/TabBar_Symbol/Issue_Symbol.imageset/Issue_Symbol.svg
  iOS/issue-tracker/issue-tracker/Assets.xcassets/TabBar_Symbol/Label_Symbol.imageset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/TabBar_Symbol/Label_Symbol.imageset/Label_Symbol.svg
  iOS/issue-tracker/issue-tracker/Assets.xcassets/TabBar_Symbol/Milestone_Symbol.imageset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/TabBar_Symbol/Milestone_Symbol.imageset/Milestone_Symbol.svg
  iOS/issue-tracker/issue-tracker/CommonTypeValue/ColorValue.swift
  iOS/issue-tracker/issue-tracker/CommonTypeValue/FontStyle.swift
  iOS/issue-tracker/issue-tracker/CommonTypeValue/SFsymbol.swift
  iOS/issue-tracker/issue-tracker/IssueFilter/IssueFilterCell.swift
  iOS/issue-tracker/issue-tracker/IssueFilter/IssueFilterHeaderView.swift
  iOS/issue-tracker/issue-tracker/IssueFilter/IssueFilterViewController.swift
  iOS/issue-tracker/issue-tracker/IssueFilter/MockHeaderData.swift
  iOS/issue-tracker/issue-tracker/IssueList/CustomLabelView.swift
  iOS/issue-tracker/issue-tracker/IssueList/IssueCardCell.swift
  iOS/issue-tracker/issue-tracker/IssueList/IssueListHeaderView.swift
  iOS/issue-tracker/issue-tracker/IssueList/IssueViewController.swift
  iOS/issue-tracker/issue-tracker/IssueViewController.swift
  iOS/issue-tracker/issue-tracker/SymbolImage.swift
  iOS/issue-tracker/issue-tracker/TabBar/TabBarType.swift
  iOS/issue-tracker/issue-tracker/TabBar/TabBarViewController.swift
  iOS/issue-tracker/issue-tracker/TabBarViewController.swift
Labels: review-ios

#40 [team- 04] BE : 감자, Birdie - Issue Tracker 2주차
  BE/.github/.gitmessage.txt
  BE/.github/workflows/deploy.yml
  BE/build.gradle
  BE/src/main/java/issuetracker/issuetracker/domain/issue/Issue.java
  BE/src/main/java/issuetracker/issuetracker/domain/issue/dto/req/IssueDTO.java
  BE/src/main/java/issuetracker/issuetracker/domain/issue/mapper/IssueRowMapper.java
  BE/src/main/java/issuetracker/issuetracker/domain/issue/repositroy/IssueRepository.java
  BE/src/main/java/issuetracker/issuetracker/domain/issue/repositroy/IssueRepositoryJDBCtem.java
  BE/src/main/java/issuetracker/issuetracker/domain/issue/service/IssueService.java
  BE/src/main/java/issuetracker/issuetracker/domain/label/Label.java
  BE/src/main/java/issuetracker/issuetracker/domain/label/LabelRepository.java
  BE/src/main/java/issuetracker/issuetracker/domain/label/dto/LabelDTO.java
  BE/src/main/java/issuetracker/issuetracker/domain/milestone/MileRepository.java
  BE/src/main/java/issuetracker/issuetracker/domain/milestone/Milestone.java
  BE/src/main/java/issuetracker/issuetracker/domain/page/PageController.java
  BE/src/main/java/issuetracker/issuetracker/domain/page/PageRepository.java
  BE/src/main/java/issuetracker/issuetracker/domain/page/PageService.java
  BE/src/main/java/issuetracker/issuetracker/domain/page/dto/CountInfo.java
  BE/src/main/java/issuetracker/issuetracker/domain/page/dto/MainPage.java
  BE/src/main/java/issuetracker/issuetracker/domain/page/dto/request/MainPageRequest.java
  BE/src/main/java/issuetracker/issuetracker/domain/user/dto/AssigneeDTO.java
  BE/src/main/java/issuetracker/issuetracker/domain/user/dto/AuthorDTO.java
  BE/src/main/java/issuetracker/issuetracker/infrastructure/config/SwaggerConfig.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/application.yml
  BE/src/main/resources/data/schma.sql
Labels: review-be

#30 [team-03] BE 2주차 리뷰 PR
  .gitignore
  .idea/.gitignore
  BE/.idea/.gitignore
  BE/HELP.md
  BE/build.gradle
  BE/src/main/java/com/example/BE/assignee/Assignee.java
  BE/src/main/java/com/example/BE/configuration/WebConfig.java
  BE/src/main/java/com/example/BE/dto/show/issue/FeIssueResponse.java
  BE/src/main/java/com/example/BE/dto/show/issue/detailed/CountForShow.java
  BE/src/main/java/com/example/BE/dto/show/issue/detailed/FeSimpleIssue.java
  BE/src/main/java/com/example/BE/dto/show/issue/detailed/SimpleAuthor.java
  BE/src/main/java/com/example/BE/dto/show/issue/detailed/SimpleLabel.java
  BE/src/main/java/com/example/BE/dto/show/issue/detailed/SimpleMilestone.java
  BE/src/main/java/com/example/BE/issue/Issue.java
  BE/src/main/java/com/example/BE/issue/IssueController.java
  BE/src/main/java/com/example/BE/issue/IssueRepository.java
  BE/src/main/java/com/example/BE/issue/IssueRepositoryCustom.java
  BE/src/main/java/com/example/BE/issue/IssueRepositoryImpl.java
  BE/src/main/java/com/example/BE/issue/IssueService.java
  BE/src/main/java/com/example/BE/issue/dto/CountDTO.java
  BE/src/main/java/com/example/BE/issue/dto/FeIssueResponseDTO.java
  BE/src/main/java/com/example/BE/issue/dto/IosIssueResponseDTO.java
  BE/src/main/java/com/example/BE/issue/dto/IssueLabelMap.java
  BE/src/main/java/com/example/BE/issue/dto/IssueNumberWithLabelDTO.java
  BE/src/main/java/com/example/BE/issue/dto/IssueSearchCondition.java
  BE/src/main/java/com/example/BE/issue/mapper/AssigneeRowMapper.java
  BE/src/main/java/com/example/BE/issue/mapper/CountRowMapper.java
  BE/src/main/java/com/example/BE/issue/mapper/IssueLabelMapRowMapper.java
  BE/src/main/java/com/example/BE/issue/mapper/IssueMapper.java
  BE/src/main/java/com/example/BE/issue/mapper/IssueWithoutLabelsRowMapper.java
  BE/src/main/java/com/example/BE/label/Label.java
  BE/src/main/java/com/example/BE/milestone/Milestone.java
  BE/src/main/java/com/example/BE/test/TestController.java
  BE/src/main/java/com/example/BE/test/TestDTO.java
  BE/src/main/java/com/example/BE/user/User.java
  BE/src/main/resources/com/example/BE/issue/mapper/IssueMapper.xml
  BE/src/main/resources/create_table.sql
  BE/src/main/resources/dummy_data.sql
  BE/src/test/java/com/example/BE/issue/IssueControllerTest.java
  BE/src/test/java/com/example/BE/issue/IssueRepositoryTest.java
  BE/src/test/java/com/example/BE/issue/IssueServiceTest.java
Labels: review-be

#35 [team-02] BE 이슈 목록 조회, 이슈 상세조회, 라벨 CRUD API 구현, AWS EC2 배포
  .gitignore
  be/src/main/java/com/issuetracker/IssueTrackerApplication.java
  be/src/main/java/com/issuetracker/controller/IssueController.java
  be/src/main/java/com/issuetracker/controller/IssueListController.java
  be/src/main/java/com/issuetracker/controller/LabelController.java
  be/src/main/java/com/issuetracker/domain/Label.java
  be/src/main/java/com/issuetracker/dto/issue/AssigneeDto.java
  be/src/main/java/com/issuetracker/dto/issue/IssueCommentDto.java
  be/src/main/java/com/issuetracker/dto/issue/IssueDetailDto.java
  be/src/main/java/com/issuetracker/dto/issue/IssueDetailPageDto.java
  be/src/main/java/com/issuetracker/dto/issue/IssueLabelDto.java
  be/src/main/java/com/issuetracker/dto/issue/IssueMilestoneDto.java
  be/src/main/java/com/issuetracker/dto/issueList/FilterLabelDto.java
  be/src/main/java/com/issuetracker/dto/issueList/FilterMilestoneDto.java
  be/src/main/java/com/issuetracker/dto/issueList/FilterUserDto.java
  be/src/main/java/com/issuetracker/dto/issueList/IssueDao.java
  be/src/main/java/com/issuetracker/dto/issueList/IssueDto.java
  be/src/main/java/com/issuetracker/dto/issueList/IssueListDto.java
  be/src/main/java/com/issuetracker/dto/label/LabelDto.java
  be/src/main/java/com/issuetracker/dto/label/LabelListDto.java
  be/src/main/java/com/issuetracker/dto/label/LabelVo.java
  be/src/main/java/com/issuetracker/repository/IssueListRepository.java
  be/src/main/java/com/issuetracker/repository/IssueRepository.java
  be/src/main/java/com/issuetracker/repository/LabelRepository.java
  be/src/main/java/com/issuetracker/service/IssueListService.java
  be/src/main/java/com/issuetracker/service/IssueService.java
  be/src/main/java/com/issuetracker/service/LabelService.java
  be/src/main/resources/application.properties
Labels: review-be

#44 [team-02] iOS: 이슈 목록 화면 및 이슈 목록 필터 적용 화면 구성, NetworkManager 구현
  .gitignore
  ios/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  ios/IssueTracker/IssueTracker/Common/Color.swift
  ios/IssueTracker/IssueTracker/Common/TypoGraphy.swift
  ios/IssueTracker/IssueTracker/DataSender.swift
  ios/IssueTracker/IssueTracker/Extension/UILabel+font.swift
  ios/IssueTracker/IssueTracker/IssueTab/IssueLabel.swift
  ios/IssueTracker/IssueTracker/IssueTab/IssueList.storyboard
  ios/IssueTracker/IssueTracker/IssueTab/IssueListCollectionViewCell.swift
  ios/IssueTracker/IssueTracker/IssueTab/IssueListCollectionViewCell.xib
  ios/IssueTracker/IssueTracker/IssueTab/IssueListFilter/FilterList.storyboard
  ios/IssueTracker/IssueTracker/IssueTab/IssueListFilter/FilterListCollectionViewCell.swift
  ios/IssueTracker/IssueTracker/IssueTab/IssueListFilter/FilterListCollectionViewCell.xib
  ios/IssueTracker/IssueTracker/IssueTab/IssueListFilter/FilterListCollectionViewHeader.swift
  ios/IssueTracker/IssueTracker/IssueTab/IssueListFilter/FilterListCollectionViewHeader.xib
  ios/IssueTracker/IssueTracker/IssueTab/IssueListFilter/FilterListViewController.swift
  ios/IssueTracker/IssueTracker/IssueTab/IssueListViewController.swift
  ios/IssueTracker/IssueTracker/IssueTab/LoadCollectionViewCell.swift
  ios/IssueTracker/IssueTracker/IssueTab/LoadCollectionViewCell.xib
  ios/IssueTracker/IssueTracker/Network/DTO/IssueListDTO.swift
  ios/IssueTracker/IssueTracker/Network/MockResponse.swift
  ios/IssueTracker/IssueTracker/Network/NetworkError.swift
  ios/IssueTracker/IssueTracker/Network/NetworkManager.swift
  ios/IssueTracker/IssueTracker/Network/URLSessionDataTaskInterface.swift
  ios/IssueTracker/IssueTracker/Network/URLSessionInterface.swift
  ios/IssueTracker/IssueTracker/Resource/issues.json
  ios/IssueTracker/IssueTracker/Supporting Files/AppDelegate.swift
  ios/IssueTracker/IssueTracker/Supporting Files/Base.lproj/LaunchScreen.storyboard
  ios/IssueTracker/IssueTracker/Supporting Files/Base.lproj/Main.storyboard
  ios/IssueTracker/IssueTracker/Supporting Files/SceneDelegate.swift
  ios/IssueTracker/IssueTracker/TabBarController.storyboard
  ios/IssueTracker/IssueTracker/TabBarController.swift
  ios/IssueTracker/IssueTracker/ViewController.swift
Labels: review-ios

#41 [team-03 FE] Week2 PR
  fe/.eslintrc.js
  fe/public/index.html
  fe/src/App.jsx
  fe/src/assets/LogotypeMedium.svg
  fe/src/assets/alertCircle.svg
  fe/src/assets/alertCircleBlue.svg
  fe/src/assets/archive.svg
  fe/src/assets/checkOffCircle.svg
  fe/src/assets/checkOnCircle.svg
  fe/src/assets/chevronDown.svg
  fe/src/assets/label.svg
  fe/src/assets/mileStone.svg
  fe/src/assets/moon.svg
  fe/src/assets/plus.svg
  fe/src/assets/search.svg
  fe/src/assets/sun.svg
  fe/src/assets/userImageLarge.svg
  fe/src/assets/userImageSmall.svg
  fe/src/components/CheckBox.jsx
  fe/src/components/DropDown.jsx
  fe/src/components/DropDown/DropDown.jsx
  fe/src/components/DropDown/DropDownContent/DropDownBody/DropDownBody.jsx
  fe/src/components/DropDown/DropDownContent/DropDownContent.jsx
  fe/src/components/DropDown/DropDownContent/DropDownHeader/DropDownHeader.jsx
  fe/src/components/DropDownBody.jsx
  fe/src/components/DropDownHead.jsx
  fe/src/components/DropDownItem.jsx
  fe/src/components/FilterBar.jsx
  fe/src/components/FilterButton.jsx
  fe/src/components/FilterInput.jsx
  fe/src/components/GlobalStyles.jsx
  fe/src/components/IssueItem.jsx
  fe/src/components/IssueList.jsx
  fe/src/components/IssueStatusButtons.jsx
  fe/src/components/IssueTable.jsx
  fe/src/components/IssueTable/CheckBox/CheckBox.jsx
  fe/src/components/IssueTable/IssueItem/IssueItem.jsx
  fe/src/components/IssueTable/IssueTable.jsx
  fe/src/components/IssueTable/TableToolBar/IssueStatusButtons/IssueStatusButtons.jsx
  fe/src/components/IssueTable/TableToolBar/TableFilterButtons/TableFilterButtons.jsx
  fe/src/components/IssueTable/TableToolBar/TableToolBar.jsx
  fe/src/components/TabBar/FilterBar/FilterBar.jsx
  fe/src/components/TabBar/FilterBar/FilterInput/FilterInput.jsx
  fe/src/components/TabBar/NavTab/NabTab.jsx
  fe/src/components/TabBar/TabBar.jsx
  fe/src/components/TableToolBar.jsx
  fe/src/components/common/Button/Button.jsx
  fe/src/components/common/ChevronDown/ChevronDown.jsx
  fe/src/components/common/Header/Header.jsx
  fe/src/components/common/Label/Label.jsx
  fe/src/components/common/PageLayout/PageLayout.jsx
  fe/src/components/common/Toggle/Toggle.jsx
  fe/src/components/common/UserIcon/UserIcon.jsx
  fe/src/components/common/index.js
  fe/src/constants.js
  fe/src/style/GlobalStyles.jsx
  fe/src/style/darkTheme.js
  fe/src/style/font.js
  fe/src/style/index.js
  fe/src/style/lightTheme.js
Labels: review-fe

#28 [team-01] BE 2주차 리뷰 PR
  .DS_Store
  .gitignore
  .idea/.gitignore
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .travis.yml
  BE/appspec.yml
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/scripts/deploy.sh
  BE/settings.gradle
  BE/src/main/java/team01/issuetracker/IssueTrackerApplication.java
  BE/src/main/java/team01/issuetracker/domain/Comment.java
  BE/src/main/java/team01/issuetracker/domain/Issue.java
  BE/src/main/java/team01/issuetracker/repository/IssueRepository.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
  BE/src/test/java/team01/issuetracker/IssueTrackerApplicationTests.java
  BE/src/test/java/team01/issuetracker/repository/IssueRepositoryTest.java
  BE/src/test/resources/application.properties
  BE/src/test/resources/data.sql
  BE/src/test/resources/schema.sql
  README.md
Labels: review-be

#63 [team-03 : iOS] 3주차 서버에서 이슈 목록 조회, 필터 기능 및 이슈 선택 기능 구현
  iOS/issue-tracker/.swiftlint.yml
  iOS/issue-tracker/issue-tracker.xcodeproj/project.pbxproj
  iOS/issue-tracker/issue-tracker/Home/HomeStoryboard.storyboard
  iOS/issue-tracker/issue-tracker/Home/Issue/Controllers/IssueFilterTableViewController.swift
  iOS/issue-tracker/issue-tracker/Home/Issue/Controllers/IssueTabViewController.swift
  iOS/issue-tracker/issue-tracker/Home/Issue/Models/FilterOption.swift
  iOS/issue-tracker/issue-tracker/Home/Issue/Models/FilterOptionListMock.swift
  iOS/issue-tracker/issue-tracker/Home/Issue/Models/IssueFrame.swift
  iOS/issue-tracker/issue-tracker/Home/Issue/Models/IssueFrameHolder.swift
  iOS/issue-tracker/issue-tracker/Home/Issue/Models/Milestone.swift
  iOS/issue-tracker/issue-tracker/Home/Issue/Views/AddIssueButton.swift
  iOS/issue-tracker/issue-tracker/Home/Issue/Views/BadgeLabel.swift
  iOS/issue-tracker/issue-tracker/Home/Issue/Views/IssueCollectionView.swift
  iOS/issue-tracker/issue-tracker/Home/Issue/Views/IssueCollectionViewCell.swift
  iOS/issue-tracker/issue-tracker/Home/Issue/Views/IssueCollectionViewCell.xib
  iOS/issue-tracker/issue-tracker/Home/Issue/Views/IssueCollectionViewHeaderCell.swift
  iOS/issue-tracker/issue-tracker/Home/Issue/Views/IssueCollectionViewHeaderCell.xib
  iOS/issue-tracker/issue-tracker/Home/Issue/Views/IssueFilterTableViewCell.swift
  iOS/issue-tracker/issue-tracker/Home/Issue/Views/IssueSelectingToolbar.swift
  iOS/issue-tracker/issue-tracker/Home/Issue/Views/SubIconView.swift
  iOS/issue-tracker/issue-tracker/Networking/NetworkManager.swift
Labels: review-ios

#55 [team-02] BE 이슈 목록 조회, 이슈 상세조회, 라벨 CRUD API 구현, AWS EC2 배포
  README.md
  be/build.gradle
  be/src/main/java/com/issuetracker/configuration/CorsConfigurer.java
  be/src/main/java/com/issuetracker/controller/CommentController.java
  be/src/main/java/com/issuetracker/controller/IssueController.java
  be/src/main/java/com/issuetracker/controller/IssueListController.java
  be/src/main/java/com/issuetracker/controller/LabelController.java
  be/src/main/java/com/issuetracker/controller/MilestoneController.java
  be/src/main/java/com/issuetracker/domain/Assignee.java
  be/src/main/java/com/issuetracker/domain/Comment.java
  be/src/main/java/com/issuetracker/domain/Issue.java
  be/src/main/java/com/issuetracker/domain/IssueLabel.java
  be/src/main/java/com/issuetracker/domain/IssueListPage.java
  be/src/main/java/com/issuetracker/domain/Label.java
  be/src/main/java/com/issuetracker/domain/Milestone.java
  be/src/main/java/com/issuetracker/domain/User.java
  be/src/main/java/com/issuetracker/dto/comment/CommentPostDto.java
  be/src/main/java/com/issuetracker/dto/issue/AssigneeDto.java
  be/src/main/java/com/issuetracker/dto/issue/IssueCommentDto.java
  be/src/main/java/com/issuetracker/dto/issue/IssueDetailDto.java
  be/src/main/java/com/issuetracker/dto/issue/IssueDetailPageDto.java
  be/src/main/java/com/issuetracker/dto/issue/IssueLabelDto.java
  be/src/main/java/com/issuetracker/dto/issue/IssueMilestone.java
  be/src/main/java/com/issuetracker/dto/issue/IssueMilestoneDto.java
  be/src/main/java/com/issuetracker/dto/issue/IssuePostDto.java
  be/src/main/java/com/issuetracker/dto/issue/IssueStatusDto.java
  be/src/main/java/com/issuetracker/dto/issue/UserDto.java
  be/src/main/java/com/issuetracker/dto/issueList/Filter.java
  be/src/main/java/com/issuetracker/dto/issueList/FilterLabelDto.java
  be/src/main/java/com/issuetracker/dto/issueList/FilterMilestoneDto.java
  be/src/main/java/com/issuetracker/dto/issueList/FilterUserDto.java
  be/src/main/java/com/issuetracker/dto/issueList/IssueDto.java
  be/src/main/java/com/issuetracker/dto/issueList/IssueListDto.java
  be/src/main/java/com/issuetracker/dto/issueList/IssueStatusListDto.java
  be/src/main/java/com/issuetracker/dto/label/LabelDto.java
  be/src/main/java/com/issuetracker/dto/label/LabelListDto.java
  be/src/main/java/com/issuetracker/dto/label/LabelVo.java
  be/src/main/java/com/issuetracker/dto/milestone/MilestoneDto.java
  be/src/main/java/com/issuetracker/dto/milestone/MilestonePageDto.java
  be/src/main/java/com/issuetracker/mapper/FilterListMapper.java
  be/src/main/java/com/issuetracker/mapper/IssueListDtoMapper.java
  be/src/main/java/com/issuetracker/mapper/IssueListMapper.java
  be/src/main/java/com/issuetracker/mapper/JacksonLocalDateTimeConfig.java
  be/src/main/java/com/issuetracker/mapper/LabelToDtoMapper.java
  be/src/main/java/com/issuetracker/repository/AssigneeRepository.java
  be/src/main/java/com/issuetracker/repository/CommentRepository.java
  be/src/main/java/com/issuetracker/repository/IssueLabelRepository.java
  be/src/main/java/com/issuetracker/repository/IssueListRepository.java
  be/src/main/java/com/issuetracker/repository/IssueRepository.java
  be/src/main/java/com/issuetracker/repository/LabelRepository.java
  be/src/main/java/com/issuetracker/repository/MilestoneRepository.java
  be/src/main/java/com/issuetracker/repository/UserRepository.java
  be/src/main/java/com/issuetracker/service/CommentService.java
  be/src/main/java/com/issuetracker/service/IssueListService.java
  be/src/main/java/com/issuetracker/service/IssueService.java
  be/src/main/java/com/issuetracker/service/LabelService.java
  be/src/main/java/com/issuetracker/service/MilestoneService.java
  be/src/main/resources/com/issuetracker/mapper/IssueListMapper.xml
Labels: review-be

#57 [team-01] iOS 3주차 PR
  iOS/.gitignore
  iOS/Issue-tracker/.swiftlint.yml
  iOS/Issue-tracker/Issue-tracker.xcodeproj/project.pbxproj
  iOS/Issue-tracker/Issue-tracker/FilterIssueTable/CustomNaviFilter.swift
  iOS/Issue-tracker/Issue-tracker/FilterIssueTable/FilterTableViewController.swift
  iOS/Issue-tracker/Issue-tracker/Help/NameSpace.swift
  iOS/Issue-tracker/Issue-tracker/Help/UIColor+Extension.swift
  iOS/Issue-tracker/Issue-tracker/IssueList/CollectionHeaderView.swift
  iOS/Issue-tracker/Issue-tracker/IssueList/IssueCell.swift
  iOS/Issue-tracker/Issue-tracker/IssueList/IssueListCollectionViewController.swift
  iOS/Issue-tracker/Issue-tracker/IssueList/PaddingLabel.swift
  iOS/Issue-tracker/Issue-tracker/Network/IssueData.swift
  iOS/Issue-tracker/Issue-tracker/Network/NetworkManager.swift
  iOS/Issue-tracker/Issue-tracker/Network/PrivateURL.swift
  iOS/Issue-tracker/Issue-tracker/Resource/Assets.xcassets/issueImage.imageset/Contents.json
  iOS/Issue-tracker/Issue-tracker/Resource/Assets.xcassets/issueImage.imageset/issueImage.svg
  iOS/Issue-tracker/Issue-tracker/Resource/Assets.xcassets/labelImage.imageset/Contents.json
  iOS/Issue-tracker/Issue-tracker/Resource/Assets.xcassets/labelImage.imageset/labelImage.svg
  iOS/Issue-tracker/Issue-tracker/Resource/Assets.xcassets/milestoneImage.imageset/Contents.json
  iOS/Issue-tracker/Issue-tracker/Resource/Assets.xcassets/milestoneImage.imageset/milsoneImage.svg
  iOS/Issue-tracker/Issue-tracker/TabBarViewController.swift
  iOS/Issue-tracker/Podfile
  iOS/Issue-tracker/Podfile.lock
Labels: review-ios

#56 [team-01] FE 3주차 리뷰 PR
  fe/.gitignore
  fe/package-lock.json
  fe/package.json
  fe/src/App.js
  fe/src/assets/icons/CancelIcon.svg
  fe/src/assets/icons/CheckOffCircle.svg
  fe/src/assets/icons/CheckOnCircle.svg
  fe/src/assets/icons/DropdownIcon.svg
  fe/src/components/addIssuePage/addIssueButtons/Buttons.jsx
  fe/src/components/addIssuePage/addIssueMainContent/AddIssueMainContent.jsx
  fe/src/components/addIssuePage/addIssueMainContent/Inputs.jsx
  fe/src/components/addIssuePage/addIssueMainContent/Sidebar.jsx
  fe/src/components/common/button/Button.jsx
  fe/src/components/common/checkbox/Checkbox.jsx
  fe/src/components/common/dropdown/Dropdown.jsx
  fe/src/components/common/dropdown/dropdownContent/DropdownButton.jsx
  fe/src/components/common/dropdown/dropdownContent/DropdownPanel.jsx
  fe/src/components/common/header/Header.jsx
  fe/src/components/common/layout/PageLayout.jsx
  fe/src/components/common/tabs/Tabs.jsx
  fe/src/components/mainPage/issueTable/IssueTable.jsx
  fe/src/components/mainPage/issueTable/header/IssueTableHeader.jsx
  fe/src/components/mainPage/issueTable/header/headerLeft/IssueTableHeaderLeft.jsx
  fe/src/components/mainPage/issueTable/header/headerRight/IssueFilterButton.jsx
  fe/src/components/mainPage/issueTable/header/headerRight/IssueTableHeaderRight.jsx
  fe/src/components/mainPage/issueTable/header/issueFilterOptions/IssueFilterOptions.jsx
  fe/src/components/mainPage/issueTable/header/issueStateFilter/IssueStateButton.jsx
  fe/src/components/mainPage/issueTable/header/issueStateFilter/IssueStateFilter.jsx
  fe/src/components/mainPage/issueTable/list/IssueTableList.jsx
  fe/src/components/mainPage/issueTable/list/listItems/IssueTableListItem.jsx
  fe/src/components/mainPage/issueTable/list/listItems/listItemLeft/ListItemLeft.jsx
  fe/src/components/mainPage/issueTable/list/listItems/listItemLeft/listItemLeftContent/LeftContentBottom/IssueInfo.jsx
  fe/src/components/mainPage/issueTable/list/listItems/listItemLeft/listItemLeftContent/LeftContentBottom/LeftContentBottom.jsx
  fe/src/components/mainPage/issueTable/list/listItems/listItemLeft/listItemLeftContent/LeftContentTop/IssueTitle.jsx
  fe/src/components/mainPage/issueTable/list/listItems/listItemLeft/listItemLeftContent/LeftContentTop/Label.jsx
  fe/src/components/mainPage/issueTable/list/listItems/listItemLeft/listItemLeftContent/LeftContentTop/LeftContentTop.jsx
  fe/src/components/mainPage/issueTable/list/listItems/listItemLeft/listItemLeftContent/ListItemLeftContent.jsx
  fe/src/components/mainPage/issueTable/list/listItems/listItemRight/ListItemRight.jsx
  fe/src/components/mainPage/issueTable/list/listItems/listItemRight/UserIcon.jsx
  fe/src/components/mainPage/nav/Nav.jsx
  fe/src/index.js
  fe/src/mocks/handler.js
  fe/src/pages/AddIssuePage.jsx
  fe/src/pages/MainPage.jsx
  fe/src/styles/GlobalStyle.jsx
  fe/src/utils/api/api.js
  fe/src/utils/api/timeElapsed.js
Labels: review-fe

#47 [TEAM-05][BE : NINO,고뭉남] Issue-Tracker 3주차 PR
  BE/src/main/java/team05/codesquad/issuetracker/auth/AWSCredentialsProperties.java
  BE/src/main/java/team05/codesquad/issuetracker/auth/S3Properties.java
  BE/src/main/java/team05/codesquad/issuetracker/config/AmazonS3Config.java
  BE/src/main/java/team05/codesquad/issuetracker/config/S3Uploader.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/IssueController.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/LabelController.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/MilestoneController.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/S3TestController.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/issuedto/IssueRequest.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/issuedto/IssueResponse.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/issuedto/IssuesResponse.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/labeldto/LabelRequest.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/labeldto/LabelResponse.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/labeldto/LabelsResponse.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/milestonedto/MilestoneDto.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/milestonedto/request/MilestoneCreateRequest.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/milestonedto/request/MilestoneUpdateRequest.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/milestonedto/response/MilestoneCreateResponse.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/milestonedto/response/MilestoneListResponse.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/milestonedto/response/MilestoneUpdateResponse.java
  BE/src/main/java/team05/codesquad/issuetracker/domain/issue/Issue.java
  BE/src/main/java/team05/codesquad/issuetracker/domain/issue/IssueRefLabel.java
  BE/src/main/java/team05/codesquad/issuetracker/domain/label/Label.java
  BE/src/main/java/team05/codesquad/issuetracker/domain/milestone/Milestone.java
  BE/src/main/java/team05/codesquad/issuetracker/repository/IssueRepository.java
  BE/src/main/java/team05/codesquad/issuetracker/repository/LabelRepository.java
  BE/src/main/java/team05/codesquad/issuetracker/repository/MilestoneRepository.java
  BE/src/main/java/team05/codesquad/issuetracker/service/IssueService.java
  BE/src/main/java/team05/codesquad/issuetracker/service/LabelService.java
  BE/src/main/java/team05/codesquad/issuetracker/service/MilestoneService.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
Labels: review-be

#49 [team-02] FE 3주차 PR
  .gitignore
  fe/.gitignore
  fe/package-lock.json
  fe/package.json
  fe/src/App.tsx
  fe/src/api.ts
  fe/src/common/Button/index.tsx
  fe/src/common/FilterItem/FilterItem.stories.ts
  fe/src/common/FilterItem/FilterItem.tsx
  fe/src/common/Profile/index.tsx
  fe/src/common/Tag/index.tsx
  fe/src/components/FilterBar/FilterBar.stories.ts
  fe/src/components/FilterBar/FilterBar.tsx
  fe/src/components/FilterList/FilterList.stories.ts
  fe/src/components/FilterList/FilterList.tsx
  fe/src/components/Header/Header.tsx
  fe/src/components/IssueCommentInput/IssueCommentInput.tsx
  fe/src/components/IssueCommentItem/IssueCommentItem.tsx
  fe/src/components/IssueCommentList/IssueCommentList.tsx
  fe/src/components/IssueController/IssueController.tsx
  fe/src/components/IssueMainInfo/IssueMainInfo.tsx
  fe/src/components/IssueSubInfo/IssueSubInfo.tsx
  fe/src/components/IssueTable/Issue.stories.ts
  fe/src/components/IssueTable/Issue.tsx
  fe/src/components/IssueTable/IssueTable.stories.ts
  fe/src/components/IssueTable/IssueTable.tsx
  fe/src/components/MilestoneProgressBar/MilestoneProgressBar.tsx
  fe/src/components/NavLinks/NavLinks.tsx
  fe/src/constants/Constants.ts
  fe/src/customTypes/IssueDetailPage.ts
  fe/src/mocks/temp.ts
  fe/src/pages/ErrorPage.tsx
  fe/src/pages/IssueDetailPage.tsx
  fe/src/pages/MainPage.tsx
  fe/src/pages/RootPage.tsx
  fe/src/utils/getTimeElapsed.ts
  fe/tsconfig.json
  fe/tsconfig.paths.json
Labels: review-fe

#64 [team-04] 이슈 목록 화면 구성 및 테스트 코드 작성
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Application/AppDelegate.swift
  iOS/IssueTracker/IssueTracker/Application/AppDependency.swift
  iOS/IssueTracker/IssueTracker/Application/CompositionRoot.swift
  iOS/IssueTracker/IssueTracker/Application/SceneDelegate.swift
  iOS/IssueTracker/IssueTracker/Application/main.swift
  iOS/IssueTracker/IssueTracker/Domain/UseCase/Common/Entity/User.swift
  iOS/IssueTracker/IssueTracker/Domain/UseCase/Issue/Entity/Issue.swift
  iOS/IssueTracker/IssueTracker/Domain/UseCase/Issue/Entity/IssueCollection.swift
  iOS/IssueTracker/IssueTracker/Domain/UseCase/Issue/Protocol/IssueListUseCaseType.swift
  iOS/IssueTracker/IssueTracker/Domain/UseCase/Milestone/Entity/Milestone.swift
  iOS/IssueTracker/IssueTracker/Global/Extension/UICollectionReusableView+Extension.swift
  iOS/IssueTracker/IssueTracker/Global/Literal/ComponentStyle.swift
  iOS/IssueTracker/IssueTracker/Global/Literal/FontStyle.swift
  iOS/IssueTracker/IssueTracker/Global/Literal/LoadingStatus.swift
  iOS/IssueTracker/IssueTracker/Global/Literal/Rgb.swift
  iOS/IssueTracker/IssueTracker/Global/Literal/StoryBoardLiteral.swift
  iOS/IssueTracker/IssueTracker/Global/Literal/StringLiteral.swift
  iOS/IssueTracker/IssueTracker/Global/Util/Factory/IssueListViewControllerFactory.swift
  iOS/IssueTracker/IssueTracker/Global/Util/Factory/NibFactory.swift
  iOS/IssueTracker/IssueTracker/Global/Util/Factory/Protocol/ViewControllerMakable.swift
  iOS/IssueTracker/IssueTracker/Presentation/Common/View/Base.lproj/IssueTrackerTabBar.storyboard
  iOS/IssueTracker/IssueTracker/Presentation/Common/ViewController/IssueTrackerTabBarController.swift
  iOS/IssueTracker/IssueTracker/Presentation/Issue/Protocol/IssueListViewModelable.swift
  iOS/IssueTracker/IssueTracker/Presentation/Issue/View/HexConverter.swift
  iOS/IssueTracker/IssueTracker/Presentation/Issue/View/Issue.storyboard
  iOS/IssueTracker/IssueTracker/Presentation/Issue/View/IssueListCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/Presentation/Issue/View/IssueListCollectionViewCell.xib
  iOS/IssueTracker/IssueTracker/Presentation/Issue/View/IssueListView.swift
  iOS/IssueTracker/IssueTracker/Presentation/Issue/View/LabelTag.swift
  iOS/IssueTracker/IssueTracker/Presentation/Issue/ViewController/IssueListViewController.swift
  iOS/IssueTracker/IssueTracker/Presentation/Issue/ViewModel/IssueListViewModel.swift
  iOS/IssueTracker/IssueTracker/Presentation/Label/View/LabelCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/Presentation/Label/ViewController/LabelCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/Presentation/Milestone/View/MilestoneCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/Presentation/Milestone/ViewController/MilestoneCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/Resource/Info.plist
  iOS/IssueTracker/IssueTrackerTests/IssueTrackerAppDelegateTests/AppDelegateTests.swift
  iOS/IssueTracker/IssueTrackerTests/IssueTrackerAppDelegateTests/TestDouble/AppDelegateTestDouble.swift
  iOS/IssueTracker/IssueTrackerTests/IssueTrackerViewModelTests/Issue/IssueListViewModelTest.swift
  iOS/IssueTracker/IssueTrackerTests/IssueTrackerViewModelTests/Issue/Mock/MockIssueListUseCase.swift
Labels: review-ios

#51 [team-05] iOS Diffable Data Source 구현
  iOS/issue-tracker/issue-tracker.xcodeproj/project.pbxproj
  iOS/issue-tracker/issue-tracker/DiffableDataSourceManager.swift
  iOS/issue-tracker/issue-tracker/DummyData.swift
  iOS/issue-tracker/issue-tracker/HTTPHandler.swift
  iOS/issue-tracker/issue-tracker/IssueFilter/IssueFilterCell.swift
  iOS/issue-tracker/issue-tracker/IssueFilter/IssueFilterHeaderView.swift
  iOS/issue-tracker/issue-tracker/IssueFilter/IssueFilterViewController.swift
  iOS/issue-tracker/issue-tracker/IssueFilter/IsuueFilterData.swift
  iOS/issue-tracker/issue-tracker/IssueFilter/MockHeaderData.swift
  iOS/issue-tracker/issue-tracker/IssueList/CustomCapsuleLabel.swift
  iOS/issue-tracker/issue-tracker/IssueList/CustomLabelView.swift
  iOS/issue-tracker/issue-tracker/IssueList/IssueCardCell.swift
  iOS/issue-tracker/issue-tracker/IssueList/IssueListHeaderView.swift
  iOS/issue-tracker/issue-tracker/IssueList/IssueListSectionData.swift
  iOS/issue-tracker/issue-tracker/IssueList/IssueViewController.swift
Labels: review-ios

#52 [team-03] FE 3주차 PR
  fe/package-lock.json
  fe/package.json
  fe/src/App.jsx
  fe/src/assets/alertCircleBlue.svg
  fe/src/assets/checkBoxActive.svg
  fe/src/assets/checkBoxDisable.svg
  fe/src/assets/checkBoxInitial.svg
  fe/src/assets/fileIcon.svg
  fe/src/assets/grip.svg
  fe/src/assets/mileStone.svg
  fe/src/assets/xSquare.svg
  fe/src/components/Comment/Comment.jsx
  fe/src/components/CommentList/CommentList.jsx
  fe/src/components/CommentTextArea/CommentTextArea.jsx
  fe/src/components/DropDown/DropDown.jsx
  fe/src/components/DropDown/DropDownContent/DropDownBody/DropDownBody.jsx
  fe/src/components/DropDown/DropDownContent/DropDownContent.jsx
  fe/src/components/IssueTable/CheckBox/CheckBox.jsx
  fe/src/components/IssueTable/IssueItem/IssueItem.jsx
  fe/src/components/IssueTable/IssueTable.jsx
  fe/src/components/IssueTable/TableToolBar/IssueStatusButtons/IssueStatusButtons.jsx
  fe/src/components/IssueTable/TableToolBar/TableFilterButtons/TableFilterButtons.jsx
  fe/src/components/SideBar/SideBar.jsx
  fe/src/components/TabBar/FilterBar/FilterBar.jsx
  fe/src/components/TabBar/FilterBar/FilterInput/FilterInput.jsx
  fe/src/components/TabBar/NavTab/NabTab.jsx
  fe/src/components/TabBar/TabBar.jsx
  fe/src/components/TitleInput/TitleInput.jsx
  fe/src/components/common/Button/Button.jsx
  fe/src/components/common/ChevronDown/ChevronDown.jsx
  fe/src/components/common/Header/Header.jsx
  fe/src/components/common/PageLayout/PageLayout.jsx
  fe/src/components/common/Spinner/Spinner.jsx
  fe/src/components/common/index.js
  fe/src/constants.js
  fe/src/context/MainPage/MainPageActionTypes.js
  fe/src/context/MainPage/MainPageActions.js
  fe/src/context/MainPage/MainPageContext.jsx
  fe/src/hooks/useInputFocus.jsx
  fe/src/pages/AddIssue.jsx
  fe/src/pages/IssueDetail.jsx
  fe/src/pages/IssueList.jsx
  fe/src/style/GlobalStyles.jsx
  fe/src/utils/utils.js
Labels: review-fe
